import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

import { Poppins } from 'next/font/google'
import Sidebar from "@/components/sidebar";
import {user} from "../variables_functions"
import Header from "@/components/header";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <Sidebar className="hidden lg:flex" user={user} />
        <div className="flex flex-col bg-[#E3EDF9] flex-1 overflow-hidden">
          <Header />
          <main className="flex flex-col px-[clamp(15px,5%,80px)]">
            {children}

          </main>
        </div>
      </body>
    </html>
  );
}